__title__ = 'Mayan EDMS'
__version__ = '4.11.1'
__build__ = 0x041100
__build_string__ = 'v4.11-67-g8246a799632_Tue Mar 3 20:46:53 2026 -0400'
__django_version__ = '5.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2026 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
